apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  annotations:
    argocd.argoproj.io/sync-wave: "30"
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: vault
    server: "https://kubernetes.default.svc"
  source:
    path: ""
    repoURL: "https://ricoberger.github.io/helm-charts"
    targetRevision: 1.7.1
    chart: vault-secrets-operator
    helm:
      parameters:
        - name: vault.address
          value: "http://vault-server-active:8200"
        - name: vault.authMethod
          value: "kubernetes"
        - name: vault.kubernetesPath
          value: "auth/kubernetes"
        - name: vault.kubernetesRole
          value: "vault-secrets-operator"
  project: cluster-config
  syncPolicy:
    automated:
      automated:
        prune: false
        selfHeal: false
