apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-initializer-role
  namespace: vault
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]