apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-main
  namespace: openshift-monitoring
spec:
  encryptedData:
    alertmanager.yaml: AgBMbYnhEZuu7pvGizv3JJ5cwgCfiWgI28j++FW2ssI77ujwff6NFvpg8k7dqAdP7hW1ZoEtufFwUN/bcKwQ2Y1QHJuVJosNCiuGR6M/jUG+AGSmBhg4Tw6Od4bcId0SB5dlQaRLA51on5l9k14AhhrsmBZLhrkuUIhhm1LWe+84OaWt/CQv3isfErtUBZblXefWkRGq567kb05E1Pwo4AWyWHKMaojDof1XqzlSWwu+Ok0dJ8MHSV+yAF0HyiUk8Gg2kKLQ6v1jbcFsKuBhbs8/nD8QAmeMMx+BaVfEZ+QAU4TFligaMBSCQ4EwV8vPYho0+F+aOeLQkPZxYES8SSp8bk+LYBEEqB6LiiXvRvLKAlV7WAcqfmssPk+Hk4wVyo0LpfHmRhEOzTIV9mpbRDa/U+uBIMGsH2QsWAaikQwJ2LGwbFXUAfLyNhSwdHRqIAxgiub5VPOLpvVp2El4cKDjwpdXCQL1vtkBErt5cKBVqR4HfgPfvZWHHMy1IHqGePUVpMH6CK3vfs/aGHERiBcrp63LeYOn1F9jGD/9z8BmtWZbnPGfFy1016XXSeO/8hAZkqzDhvXEIr8G52nWBq6Al6fj/1azHfsCchPepyKJH7UIgb3GE38zRb+7GD8F4CHzB17T8P+t6GfOHlzl9aHbJzCkaBQC241qeVPQCnAj/ZXuYtP2Ixed8l7prJD0pME=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
      creationTimestamp: null
      name: alertmanager-main
      namespace: openshift-monitoring
    type: Opaque
