apiVersion: v1
kind: Endpoints
metadata:
  name: nfs-server
subsets:
  - addresses:
      - ip: 192.168.1.122
    ports:
      - port: 111
        name: tcp-portmapper
      - port: 2049
        name: tcp-nfs
      - port: 1110
        name: tcp-cluster-status
      - port: 4045
        name: tcp-nfs-lock
