apiVersion: v1
kind: Service
metadata:
  name: nfs-server
spec:
  ports:
    - protocol: TCP
      port: 111
      targetPort: 111
      name: tcp-portmapper
    - protocol: UDP
      port: 111
      targetPort: 111
      name: udp-portmapper
    - protocol: TCP
      port: 2049
      targetPort: 2049
      name: tcp-nfs
    - protocol: UDP
      port: 2049
      targetPort: 2049
      name: udp-nfs
    - protocol: TCP
      port: 1110
      targetPort: 1110
      name: tcp-cluster-status
    - protocol: UDP
      port: 1110
      targetPort: 1110
      name: udp-client-status
    - protocol: TCP
      port: 4045
      targetPort: 4045
      name: tcp-nfs-lock
    - protocol: UDP
      port: 4045
      targetPort: 4045
      name: udp-nfs-lock
