
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo
    kanister.kasten.io/inject-sidecar: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo-container
        image: alpine:3.7
        resources:
            requests:
              memory: 256Mi
              cpu: 100m
        command: ["tail"]
        args: ["-f", "/dev/null"]
        volumeMounts:
        - name: data
          mountPath: /data
        - name: media
          mountPath: /media
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: paperless-ng-data
      - name: media
        persistentVolumeClaim:
          claimName: paperless-ng-media