apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-service
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: nfs
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/configs/external-nfs-service
    repoURL: https://github.com/pixeljonas/cluster-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
