apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

resources:
  - google-secret.yaml
  - login-template-secret.yaml
  - provider-selection-template-secret.yaml

patchesStrategicMerge:
  - oauth-templates.yaml

patchesJson6902:
  - target:
      group: config.openshift.io
      version: v1
      kind: OAuth
      name: cluster
    path: oauth-rh-sso.yaml
