- op: add
  path: /spec/identityProviders/-
  value:
    google:
      clientID: 478348800225-pipjo1969ga8rg53sf9he8mb0sjkml01.apps.googleusercontent.com
      clientSecret:
        name: google-secret
      hostedDomain: redhat.com
    mappingMethod: claim
    name: RedHatSSO
    type: Google
- op: add
  path: /spec/identityProviders/-
  value:
    github:
      clientID: "2df4ad40a1cb85c00524"
      clientSecret:
        name: github-secret
      organizations:
        - AvengersVsVirus
    mappingMethod: claim
    name: GitHub
    type: GitHub
