apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 50-master-ntp-chrony-conf
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,c2VydmVyIDAuZGUucG9vbC5udHAub3JnIGlidXJzdApzZXJ2ZXIgMS5kZS5wb29sLm50cC5vcmcgaWJ1cnN0CnNlcnZlciAyLmRlLnBvb2wubnRwLm9yZyBpYnVyc3QKc2VydmVyIDMuZGUucG9vbC5udHAub3JnIGlidXJzdApzdHJhdHVtd2VpZ2h0IDAKZHJpZnRmaWxlIC92YXIvbGliL2Nocm9ueS9kcmlmdApydGNzeW5jCm1ha2VzdGVwIDEwIDMKYmluZGNtZGFkZHJlc3MgMTI3LjAuMC4xCmJpbmRjbWRhZGRyZXNzIDo6MQprZXlmaWxlIC9ldGMvY2hyb255LmtleXMKY29tbWFuZGtleSAxCmdlbmVyYXRlY29tbWFuZGtleQpub2NsaWVudGxvZwpsb2djaGFuZ2UgMC41CmxvZ2RpciAvdmFyL2xvZy9jaHJvbnkK
          filesystem: root
          mode: 420
          overwrite: true
          path: /etc/chrony.conf
          user:
            name: root
