apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: user-workload-grafana

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

bases:
  - cluster-role-binding-grafana-operator.yaml
  - cluster-role-grafana-operator.yaml
  - https://github.com/redhat-canada-gitops/catalog/grafana-operator/overlays/user-app?ref=grafana

patchesJson6902:
  - target:
      version: v1alpha1
      group: operators.coreos.com
      kind: Subscription
      name: grafana
    path: patch-grafana-version.yaml
