apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
  - ../base

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: config-groups-and-membership
    path: patch-groups-and-membership-app.yaml
# - target:
#     group: argoproj.io
#     version: v1alpha1
#     kind: Application
#     name: config-groups-and-membership
#   path: patch-destination.yaml
