apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-apps-micro-janz-digital
spec:
  dnsNames:
    - "*.apps.micro.janz.digital"
  secretName: wildcard-apps-micro-janz-digital-tls
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
