apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "../default"

resources:
  - "vault-cloudflare-api-token.yaml"

patches:
  - target:
      group: cert-manager.io
      version: v1alpha3
      kind: ClusterIssuer
      name: cloudflare-issuer
    path: patch-issuer-server.yaml
