apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    gitops.ownedBy: cluster-config
spec:
  destination:
    namespace: traefik
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://helm.traefik.io/traefik"
    targetRevision: 10.3.6
    chart: traefik
    helm:
      parameters:
        - name: hostNetwork
          value: "true"
        - name: ports.metrics.expose
          value: "true"
  project: cluster-config
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
