apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd-operator-system

bases:
  - ../../../manifests/argocd/apps/vault/overlays/micro
  - ../../../manifests/argocd/apps/k10/overlays/micro

resources:
  - ./cluster-apps-project.yaml

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      labelSelector: gitops.ownedBy=cluster-config
    path: patch-gitops-repo.yaml

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
    path: patch-namespace.yaml

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      labelSelector: gitops.ownedBy=cluster-config
    path: patch-target-revision.yaml

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
    path: add-finalizer.yaml
