apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox
  labels:
    app: toolbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toolbox
  template:
    metadata:
      labels:
        app: toolbox
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: toolbox
          image: chriswayg/toolbox
          command: ["/bin/sh"]
          args: ["-c", "while true; do echo hello; sleep 10;done"]  
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /usr/src/paperless/consume
              name: consume
            - mountPath: /usr/src/paperless/data
              name: data
            - mountPath: /usr/src/paperless/export
              name: export
            - mountPath: /usr/src/paperless/media
              name: media
      volumes:
        - name: consume
          persistentVolumeClaim:
            claimName: paperless-ng-import
        - name: data
          persistentVolumeClaim:
            claimName: paperless-ng-data
        - name: export
          persistentVolumeClaim:
            claimName: paperless-ng-export
        - name: media
          persistentVolumeClaim:
            claimName: paperless-ng-media
        - name: ceph-config
          emptyDir: {}
      tolerations:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 5