apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local-path-storage

resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - serviceaccount.yaml
  - config.yaml
  - storageclass.yaml
  - deployment.yaml
