apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
   app: keycloak
spec:
  instances: 1
  storageClassName: local-path
  externalAccess:
    enabled: True
    host: sso.apps.hive.janz.digital