apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k10
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "12"
spec:
  destination:
    namespace: kasten-io
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    chart: k10
    helm:
      parameters:
      values: |-
        global:
          ingress:
            create: true
            urlPath: k10
          persistence:	
            enabled: true	
            storageClass: "local-path"

        ingress:
          class: nginx
          create: true
          tls:
            enabled: true
            secretName: kasten-tls
          host: kasten.apps.hive.janz.digital
          urlPath: k10
        
        prometheus:	
          server:	
            persistentVolume:	
              enabled: true	
              storageClass: "local-path"
        injectKanisterSidecar:
          enabled: true
          objectSelector:
            matchLabels:
              kanister.kasten.io/inject-sidecar: "true"
        auth:
          basicAuth:
            enabled: true
            htpasswd: "admin:$2y$10$90kwyftHGGeNUPHiDmueqOW5/TCAWMhLjFjv9Ff111TSs.cvibk.."
    repoURL: https://charts.kasten.io/
    targetRevision: 4.0.13
  syncPolicy:
    syncOptions:
      - CreateNamespace=true