apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k10-config-app
  annotations:
    argocd.argoproj.io/sync-wave: "21"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/configs/k10/base
    repoURL: https://github.com/pixeljonas/cluster-gitops.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
