apiVersion: cert-manager.io/v1alpha3
kind: Certificate
metadata:
  name: wildcard-apps-atlantis-janz-digital
  namespace: cluster-config
spec:
  dnsNames:
    - "*.apps.atlantis.janz.digital"
  secretName: wildcard-apps-atlantis-janz-digital-tls
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer