apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cluster-config

bases:
  - "../default"

resources:
  - ingress-certificate-patch.yaml

patches:
  - patch-issuer-server.yaml
