apiVersion: cert-manager.io/v1alpha3
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer
  namespace: operators
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
#   server: https://acme-v02.api.letsencrypt.org/directory