apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgAEg22EK162e5+tYX85X7A+dwOJqRfP/pNogYFBH/pta5FeCdQZeJSpdXJ+KhKttWrH+ulPrhwQySzs/KEo0DhkrV9fLw6VomVtWRZ7jwW9x7fhrIF+hqSi/391kfI7hGjJydZX3sNtudtnGXr7LyR7/MiS65k1Ac80jweepG4m/dzUi+FknMguHjm03Y55bd6Jr8Oi98Ucsqs7TPKoU6Nrq5TTpjwoxB02VFSnRHgTmf/eNWv51pQ+MtMx3vKbav+UK1+hkopzohAybs7evii7bn8iagVbE/rLE+38DnT6OTO/OSBghIM+j8XONXuzfwRp+ROUunTtoDIi/awdFxnfAEEltwvTVNwyEUlbg5bhlMGKo4T8PVSM1KR2u25zAZmFfbr4nMNBWFQ4/lc8qHp2f6jClCe4vzA5x7J81MuUOne7yf5Gkiu/JTa67hc4U+KKCNHc6UcuraM6joLrv/XqiznFMJdeNd+kTmHMHRwey3WuNUE1uMMoJ4rEh/Mkj2ncGUDfaGxRPOEkg2n/3fG4UWvyLB6uQ/eRsQW29DBiaJCuuUWR0IObJcBp1X53TuTFR6rlx1I8tqeNg8OK70NP5YRn39UMOf+Yh4X4DCWpwEHle4wV+d5NKC9dScsmE9ZOhCWKgpMNlaD/UGS/Tiax81/iSfwaf0ZkbnwUJBCs2fVC4iHHZLNiT6EpszIHcECwiWn9egeuibRpZk3N7pytOkGBlr492tTnLL6lverFCmGRHZFpo0Ft
  template:
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
      creationTimestamp: null
      name: github-secret
      namespace: openshift-config
