apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgBUnbREX5YxuEghPGYjfXuoY2TlPyYImkt2qNo0RNv+59M/hLUrtCruxjFITkGhhK3J6wY6Sbd0rl37/XATbYrJVnnWuFJobsDpiZY58IMGmL3A5l8cpjGyR7mb0kuRc/81EW7jNBEJmpXoW3Tsi5mI/Z7watFu4O9UEBzFC/+2hmRHZifnCUWzje0nR2K26hqqsxZA1STDgmhc06QHU8/m+XDhoQRcs/n5Ga37eMuJ25eoAvt6J58CU5lqsWWJvJbOu7/JcGSxI5WxVgBv4CuzXGYEf2/9o+lmkSq09vjGbR/y1sLi9zIl5DMIAplj+Km5odbo3lH4bq5wZh5IEu+LKKOHX53Z9ivjmIklctorP6FX/4EHRnYNIn4PmprnTHCNTp89XOVrnUn4bZvKJ/iAfevuPrAaTZX815Z4aVA2S8v97suTNm6P6FNW8InzOcTmT+wMy/lp42Qk9kbxvxwVd2D+TXvXrMeTGI3bw20d+q+Zai7VGx1FLq535KM6s4k4/A6BV900gDDBlZScjod74ZHxQ8GC1UqQfZkzDsztv9XMw+n7yn6+kEKeAXBAo3D6gITdqxpNRkoA4IQ9E6ynwyeHz0++7ZbwJWsFa9jZFU1Cib73yUHnpNM/QJOGvlYKkgeno+DbHsHd7rArXAyfDlZaQKvYAlqgJZUKo5HBlkfFbSTd+uxjSr5dfTlmaUjd0uOeEVEUZEs2l3kwB3dGOvfAav4MVmHy2rhfckZcyqyiWm8mk2n7
  template:
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
      creationTimestamp: null
      name: github-secret
      namespace: openshift-config
