apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgBpftDN/ee4oF7PAxDF08oYZ0avYdqVccPs0HHe9g52cODyESAgQxfmFQ1WQGXDxuYDOk4aPQ/iPE7akYPk5rgQh0uUpqk6ZwuSGILioTWivch74dBnnNXrUNXghevNrSv5xndBjZBs5WxyLdBdhRmXoX8ViFy3SVKU0vAio0gB8E9F962SAhChD8nFEdRV/2GHdx3g7fnjqJV3s7Gjsd4W3fT2sdP7gv12LjcL783LoLc50b1u7rO9RexDe1nftQt7iv245ZWxL2nZYygzbGExTnEuQLTva4xuftHdoCkLDgE9yPVIpO0IO5A1CCW87yN5kND0X/Euh1/BgAXkSDlMlOiPJr7vg8/Yjj+NjB+cdAyBf36aBTgwb6WD/Fh4emfxruOVz32L3X0qW4D6eaFjnzFoyuh3Urg3YIXVYfsovw1syy+UW2QbAcBXN4zTzjtsKKnHXegDhpaX6nXImysHP0ox+ZRBI8rYINav47JwzcV5WnNZpICZdGEWyx7CwpVosxDDabWPO1nC9V8enLcS0tV1Qw+TTH+piUWIvs0JHWp9y3vmTTs1r9cpyuY2dRibAuw+RMfy5DNvadORa7G78cFhIYNVbjgl29BawwUiafCL2YVZ4gvV2/FabBaXJQ56vy0kmTzwDgsIgIAv3pL3U9dNxLUXOWTVKkax/E76HQ1EFV0eqI0nQLqhlzyqcUABNommFbuho36QyE6n4yXzT5xuFHFHcwLS7YcGf3/k27WpPbay/XMe
  template:
    metadata:
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
        argocd.argoproj.io/sync-options: Prune=false
      creationTimestamp: null
      name: github-secret
      namespace: openshift-config
