apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../httpasswd

resources:
  - github-secret.yaml

patchesJson6902:
  - target:
      group: config.openshift.io
      version: v1
      kind: OAuth
      name: cluster
    path: oauth-github.yaml
