apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
  - ../../../manifests/argocd/apps/sealed-secrets-operator/private
  - ../../../manifests/argocd/apps/cert-manager/overlays/private

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      labelSelector: gitops.ownedBy=cluster-config
    path: patch-gitops-repo.yaml

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      labelSelector: gitops.ownedBy=cluster-config
    path: patch-target-revision.yaml
