apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: statping-app
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-apps
  source:
    path: manifests/argocd/apps/statping/base/apps
    repoURL: https://github.com/pixeljonas/cluster-gitops.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
