kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admins-group-binding
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: admins-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
