apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
  - ../../../environments/overlays/bootstrap

resources:
  - argocd-namespace.yaml
  - clusterrolebinding.yaml
  - cluster-config-manager.yaml

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ArgoCD
      name: openshift-gitops
    path: patch-argocd-server.yaml
