apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
  - ../../../manifests/argocd/apps/oauth/public
  - ../../../manifests/argocd/apps/groups-and-membership/public
  - ../../../manifests/argocd/apps/console/public

  - ../../../manifests/argocd/apps/sealed-secrets-operator/base
  - ../../../manifests/argocd/apps/alertmanager/base
  - ../../../manifests/argocd/apps/user-workload-monitoring/base
  - ../../../manifests/argocd/apps/openshift-pipelines/base

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      labelSelector: gitops.ownedBy=cluster-config
    path: patch-gitops-repo.yaml
