apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless-ng-internet
  namespace: paperless
spec:
  ingressClassName: nginx
  rules:
  - host: paperless.janz.digital
    http:
      paths:
      - backend:
          service:
            name: paperless-ng
            port:
              number: 8000
        path: /
        pathType: Prefix


