apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

bases:
  - ../base

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: prometheus-operator
    path: patch-destination.yaml

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: prometheus-instance
    path: patch-destination.yaml

  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: prometheus-config
    path: patch-destination.yaml
