apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-config
  annotations:
    argocd.argoproj.io/sync-wave: "22"
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/configs/prometheus/base
    repoURL: https://github.com/pixeljonas/cluster-gitops.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
