apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-instance
  annotations:
    argocd.argoproj.io/sync-wave: "21"
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: manifests/
    repoURL: https://github.com/prometheus-operator/kube-prometheus.git
    targetRevision: release-0.9
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
