apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: user-workload-grafana

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

bases:
  - ../../base
  - namespace.yaml

patchesJson6902:
  - target:
      version: v1
      group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: grafana-proxy
    path: patch-proxy-namespace.yaml
  - target:
      version: v1alpha1
      group: integreatly.org
      kind: Grafana
      name: grafana
    path: patch-grafana-sar.yaml
  - target:
      version: v1
      group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: cluster-monitoring-view
    path: patch-cluster-monitoring-view.yaml
  - target:
      version: v1
      group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
      name: grafana-operator
    path: patch-cluster-role-binding.yaml
