apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: operators
spec:
  encryptedData:
    api-token: AgBwDL7hH8sY6H60lKvp24hmNgYnAO4uuYIhMlxzWWTO65+gfF1D2CxMDqQQdOk4Imk8mxZYWH9r0zHj6G/iC6i/3+S0/jkSFEWwfPegywnPaP+qs7WI9xPPGLADtpM/vUAud2spFjs5jd1BWhPAL6SjuQe/ARFIYYSirQmRF81p+sPIJcVCgpIUZDHjaY9NOvHnjt3U9jYJUVj2kAjP515Ybi23zbi0vEs7uFGl9FOz9Y0Hrp7biTNOHUOYPBy/CERN1spKlfZ3R+Too78sjcUcuLMG2SqQqnrZOE+a7ji64Peg9e94o4pd7kJacnq3wW7ZDkyhEFh25C5y4sPeaNYtrXXVnexVXd8Af9i/ICXAOBtEdAs9U3xDT7pVOOHVwjK2XdUAuksvVeH/SiPWJdkMU2o1uAqO3Rkj43q6olO4xWgKO1GhK8ynLFlm8X33/BEnirVGyr9x8+bMVA5pftOU8b9lE5FmPO+KY2ZodG8ePjHJZHAXGHfSPmEfTwdt69CZzX0MFcMAK0qUUkXo6KZCnFKOSEUsWiyNt+MhvSlXMIFOtXKkLDdpehiqDxMoQro4cJ0Y8XlJy8WkSScgreEjwoAH/pXqChE8NjX0MwrHziLYUY2hmANMW9yl5/0LTTizu3pSHPyhCTxZUFsaLQAQ9MNQ6Fh4tQU/qEWsy8Zh7uF2jnotZIfNtJWTRvrZRFUjfTuRJOu2sIpfPGgSHrnWycnvZeqZORdz2QPGkgzdHblNz45J6RaB
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: operators
