apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBFfq+u9vHXguOmkUlqYTlfDs5DiRHlhe1c+xAqM3ifphlBtwHRYvlRr45PKJ+4j9gltqfaleixtxZndMxtk5yRKpPqE8+DW6QlfzdtzU7B2/ks9pLSQSk9wpnR8T1pWiNeXWLyLXS3VmO6Qwh/9/cPRZNtLBxtX8qLhpX4xIe9DlsYoF0YuyqxhxH+QKUafB8gYuIT0QuhHDr+zw2kKSgO4ywUVr8lgucRtYp9R4N5+KlvLII+lrmFaCuUB8t1AKQo4seYnhCayZ+r6Ix3x1V8ZGi4sZvjzShiKJt1hfrYCMTZc6sEzVO0OTJKEx7dVROxgmBc11++m4CWx+JnUZ4AUG17KGjVGjcrhWsRm2Pd5qKhChoo5pIVCRfvrnO2kO8rNAZ1k+wP/fATyh9KyN0RxKazvs+1iDX+XIMNUQZhll0eZ6vJPdWQdg7oL5fJ+mSRV02l6GDPVpzdq6hu531dRpxwiPMroO2gDBUsoYK8PJRtqxWCdDTBYiFk9PuJn9ySlkuEqkm7CrG4nCqYCBmu/Gt3mABJHbrZDnHSOB0kl9HX6kEvI9bzb/7QPJp15bcO3m2pA6ff72hUkFAf3vUjR11v+eXBASn3gUyx40itYLgvT1mTRV961mrlffEOjSE51d8y56dSUD7ih+h2LG1axITr/xLBpowUKPgXduEvjAQedQ7yG5bqQcDIT/9WpKOvekaM/zJPx0Hrn/hBTP4CXfnPaEuPor/j0mrt/IAb229tHOebw01G
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: operators
