apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB9H+qWH7ZWBoq/7C8SPXC+zekg3YpTzu2HFxkQacBCrCKMqXbxJCMRhFxlKrR+Jx9Pxgion255b4P9D6m95CVi8Jqyyqqi/dQq7Z1w2TtcWP5l62Tvc6NsGoLIM0tfZ06vEaTZ+WodKCp38w5j+wkRzB1yUdfSemzvTx/NESiJ+4q6KBZr6R9Uq4JWUAYBX7gdVIn115vgb2yeNkeGyaHVe+FTCFg8uGkdPc4TlJedaakRwKxiBWBkX39MduKfXWhstHyJ+a7v4ogqWqygBa1EeA/jb/tATdC0zdEDqO4FG5DIvW5gIuTRY4BPETfoAjZYSA1HkDhjHGQnJbhT61ColsZUTVeY+zVAxf7slz8LKVYrz4cBSK0bHvQX+9Jf4Is9//eg6Ku+7qMOijsPZgpd43iysVmt4l28LbjYK60vJnF+8MiwDTKXSKy1YYQ8QWSUbBw0DtVJbGSgLRcg2n66NziUaFwB0qSiol/mvZjL0+Clacv7ycg9pdKd5lSW+SXGM/gDhyDAtlwHw/wDnm1FvLCSNB2lMaFEpgjmecplKdnV0sWbqKZ4LPXBF12RX+GNMrNYKNo0QDqrD1FEplOJkNLBYMfDvNolKIVoHqYymNQUpWNId6qyUoOBYTMSZE/qG7VrDVNz2L6lp5s5Zgrq3WnbbRtoTFE0aPbzEp7D5h6QFavkGiHnmt3nWDE3CwCyzD5IxUYOeeKplw6G1SE6bRs7h4tAxkr9p2F3t/xH/9wed3anagR5
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
