apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
spec:
  encryptedData:
    api-token: AgBrFB34ej6f5HV7bolMh6xf1llCzKIAQAqFVtyI9MDAvenVPIl3Dv/6oZ4ICB1/SnKSbo8wbX9vdIqqoyh5KH36zFZZWlDK4+D0MBlGQ2B1MGmdmV3Ikgf/me8utkKuYo+uC8NIyJcQ6+1+QJ+aY/BImUB/0yXHrnXmApQxNemHPNpsP1fyVcUbPIwnMyZ6JN0zSk0WHl0Z2fL2xC2E3F8t3bUFYOz/9/DSqNIoKdXFgscIXp/Wbma+P5LIEnGAqcX9NSJ5ApJor6+2tYWu/e3q3x5OnuXbdLKhfCwHZ9iVTvRw6m/k9E3czwZDgC127xeybRbY2NLdHpAuQRvWOQWKf3rV2SI7UNN4Y80M11XeF+y9vCSc1a42rBF0EKILL7PpZSG+f6uqnhwbcSsS186K9S11XWIwNf4xLgqnZ+5Z7HaVF8xzMbLGEEqmUlGs8Dh0mxZWtmxNETFoHsj/Tn8yGLIgyrn/YFl6qjqN2x33/VakZ18yhCnY3SmmltKFxxKd+mYlILuSx+pksaWtuURe2KCeLQEsM6OwVraCK00Lmu+JBnOg0tR+X/M/qQjJTZ3jIcqrkiTvh3ELHTl5T5jJZdeJ8j/msDyDHTpotWFUUzDA9EgzwcUsb9Lniiu3Godjkv2bHY6cT+o7/BJCD1NbpAOaAJOnLkr7wa5zQgAOjfEx/rvgGcsQyNRNP72KaVQO/EM3a6H1+GUr0cY5qvwWfeoFes3Euv/PPjbNzC0QVycMLg9uBGnZ
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: operators
